export const currencyByRupee: currency[] = [
  {
    name: 'DOLLAR',
    value: 0.012271428,
    flag: '🇺🇸',
    symbol: '$',
  },
  {
    name: 'EURO',
    value: 0.01125809,
    flag: '🇪🇺',
    symbol: '€',
  },
  {
    name: 'POUND',
    value: 0.0099194378,
    flag: '🇬🇧',
    symbol: '£',
  },
  {
    name: 'RUBEL',
    value: 0.85040469,
    flag: '🇷🇺',
    symbol: '₽',
  },
  {
    name: 'AUS DOLLAR',
    value: 0.01732574,
    flag: '🇦🇺',
    symbol: 'A$',
  },
  {
    name: 'CAN DOLLAR',
    value: 0.016457908,
    flag: '🇨🇦',
    symbol: 'C$',
  },
  {
    name: 'YEN',
    value: 1.5909089,
    flag: '🇯🇵',
    symbol: '¥',
  },
  {
    name: 'DINAR',
    value: 0.0037446993,
    flag: '🇰🇼',
    symbol: 'KD',
  },
  {
    name: 'BITCOIN',
    value: 0.000000543544886,
    flag: '🎰',
    symbol: '₿',
  },
  {
    name: 'SWISS FRANC',
    value: 0.011802,
    flag: '🇨🇭',
    symbol: 'CHF',
  },
  {
    name: 'SWEDISH KRONA',
    value: 0.106813,
    flag: '🇸🇪',
    symbol: 'kr',
  },
  {
    name: 'NORWEGIAN KRONE',
    value: 0.119019,
    flag: '🇳🇴',
    symbol: 'kr',
  },
  {
    name: 'SINGAPORE DOLLAR',
    value: 0.016112,
    flag: '🇸🇬',
    symbol: 'S$',
  },
  {
    name: 'HONG KONG DOLLAR',
    value: 0.095529,
    flag: '🇭🇰',
    symbol: 'HK$',
  },
  {
    name: 'NEW ZEALAND DOLLAR',
    value: 0.018595,
    flag: '🇳🇿',
    symbol: 'NZ$',
  },
  {
    name: 'SOUTH KOREAN WON',
    value: 14.6941,
    flag: '🇰🇷',
    symbol: '₩',
  },
  {
    name: 'BRAZILIAN REAL',
    value: 0.062847,
    flag: '🇧🇷',
    symbol: 'R$',
  },
  {
    name: 'MEXICAN PESO',
    value: 0.271104,
    flag: '🇲🇽',
    symbol: 'Mex$',
  },
  {
    name: 'CHINESE YUAN',
    value: 0.078648,
    flag: '🇨🇳',
    symbol: '¥',
  },
  {
    name: 'INDONESIAN RUPIAH',
    value: 174.62,
    flag: '🇮🇩',
    symbol: 'Rp',
  },
  {
    name: 'TURKISH LIRA',
    value: 0.179,
    flag: '🇹🇷',
    symbol: '₺',
  },
  {
    name: 'SAUDI RIYAL',
    value: 0.046849,
    flag: '🇸🇦',
    symbol: '﷼',
  },
  {
    name: 'MALAYSIAN RINGGIT',
    value: 0.050227,
    flag: '🇲🇾',
    symbol: 'RM',
  },
  {
    name: 'SOUTH AFRICAN RAND',
    value: 0.188505,
    flag: '🇿🇦',
    symbol: 'R',
  },
  {
    name: 'PHILIPPINE PESO',
    value: 0.5899,
    flag: '🇵🇭',
    symbol: '₱',
  },
  {
    name: 'THAI BAHT',
    value: 0.3837,
    flag: '🇹🇭',
    symbol: '฿',
  },
  {
    name: 'EMIRATI DIRHAM',
    value: 0.045059,
    flag: '🇦🇪',
    symbol: 'د.إ',
  },
  {
    name: 'TAIWAN DOLLAR',
    value: 0.3552,
    flag: '🇹🇼',
    symbol: 'NT$',
  },
  {
    name: 'ARGENTINE PESO',
    value: 1.1036,
    flag: '🇦🇷',
    symbol: 'ARS',
  },
  {
    name: 'EGYPTIAN POUND',
    value: 0.1926,
    flag: '🇪🇬',
    symbol: 'E£',
  },
  {
    name: 'NIGERIAN NAIRA',
    value: 4.8567,
    flag: '🇳🇬',
    symbol: '₦',
  },
  {
    name: 'POLISH ZLOTY',
    value: 0.048514,
    flag: '🇵🇱',
    symbol: 'zł',
  },
  {
    name: 'ISRAELI SHEKEL',
    value: 0.038282,
    flag: '🇮🇱',
    symbol: '₪',
  },
  {
    name: 'RUSSIAN RUBLE',
    value: 1.0242,
    flag: '🇷🇺',
    symbol: '₽',
  },
  {
    name: 'QATARI RIYAL',
    value: 0.044676,
    flag: '🇶🇦',
    symbol: 'ر.ق',
  },
  {
    name: 'HUNGARIAN FORINT',
    value: 3.8399,
    flag: '🇭🇺',
    symbol: 'Ft',
  },
  {
    name: 'CZECH KORUNA',
    value: 0.2886,
    flag: '🇨🇿',
    symbol: 'Kč',
  },
  {
    name: 'UKRAINIAN HRYVNIA',
    value: 0.3421,
    flag: '🇺🇦',
    symbol: '₴',
  },
  {
    name: 'ROMANIAN LEU',
    value: 0.06157,
    flag: '🇷🇴',
    symbol: 'lei',
  },
  {
    name: 'SRI LANKAN RUPEE',
    value: 2.4161,
    flag: '🇱🇰',
    symbol: '₨',
  },
  {
    name: 'BANGLADESHI TAKA',
    value: 1.0558,
    flag: '🇧🇩',
    symbol: '৳',
  },
  {
    name: 'VIETNAMESE DONG',
    value: 286.91,
    flag: '🇻🇳',
    symbol: '₫',
  },
  {
    name: 'MOROCCAN DIRHAM',
    value: 1.1023,
    flag: '🇲🇦',
    symbol: 'د.م.',
  },
  {
    name: 'KENYAN SHILLING',
    value: 1.3913,
    flag: '🇰🇪',
    symbol: 'KSh',
  },
  {
    name: 'COLOMBIAN PESO',
    value: 47.587,
    flag: '🇨🇴',
    symbol: 'COL$',
  },
  {
    name: 'CHILEAN PESO',
    value: 10.023,
    flag: '🇨🇱',
    symbol: 'CLP$',
  },
  {
    name: 'PERUVIAN SOL',
    value: 0.046649,
    flag: '🇵🇪',
    symbol: 'S/',
  },
  {
    name: 'CUBAN PESO',
    value: 0.30891,
    flag: '🇨🇺',
    symbol: '₱',
  },
  {
    name: 'VENEZUELAN BOLÍVAR',
    value: 268196,
    flag: '🇻🇪',
    symbol: 'Bs.S.',
  },
  {
    name: 'BOLIVIAN BOLIVIANO',
    value: 8.2766,
    flag: '🇧🇴',
    symbol: 'Bs.',
  },
  {
    name: 'PARAGUAYAN GUARANI',
    value: 84.033,
    flag: '🇵🇾',
    symbol: '₲',
  },
  {
    name: 'URUGUAYAN PESO',
    value: 0.28932,
    flag: '🇺🇾',
    symbol: '$U',
  },
  {
    name: 'GUATEMALAN QUETZAL',
    value: 0.94558,
    flag: '🇬🇹',
    symbol: 'Q',
  },
  {
    name: 'DOMINICAN PESO',
    value: 0.68138,
    flag: '🇩🇴',
    symbol: 'RD$',
  },
  {
    name: 'COSTA RICAN COLÓN',
    value: 7.7097,
    flag: '🇨🇷',
    symbol: '₡',
  },
  {
    name: 'NICARAGUAN CÓRDOBA',
    value: 0.43379,
    flag: '🇳🇮',
    symbol: 'C$',
  },
  {
    name: 'PANAMANIAN BALBOA',
    value: 0.012271428,
    flag: '🇵🇦',
    symbol: 'B/.',
  },
  {
    name: 'HONDURAN LEMPIRA',
    value: 0.30765,
    flag: '🇭🇳',
    symbol: 'L',
  },
  {
    name: 'BELIZEAN DOLLAR',
    value: 0.02474,
    flag: '🇧🇿',
    symbol: 'BZ$',
  },
  {
    name: 'JAMAICAN DOLLAR',
    value: 2.099,
    flag: '🇯🇲',
    symbol: 'J$',
  },
];
